baseURL: "https://ateon.ch"
title: "Ateon"
theme: "LoveIt"
languageCode: "en"
languageName: "English"
author:
  name: "Luca Schafroth"

menu:
  main:
    - weight: 1
      identifier: "posts"
      pre: ''
      post: ''
      name: "Posts"
      url: "/posts/"
      title: ''
    - weight: 2
      identifier: "about"
      pre: ''
      post: ''
      name: "About"
      url: "/about"
      title: ''

params:
  defaultTheme: "auto"
  dateFormat: 02.01.2006
  title: "Ateon"
  description: "Ateon"

  header:
    title:
      name: "Ateon"

  footer:
    enable: false
    hugo: false
    author: false
    since: 2021

  social:
    github: "gewlar"
    LinkedIn: "luca-schafroth-a7b9b0129"
    RSS: true
    
  app:
    title: "Ateon"

  section:
    dateFormat: "02.01"
  list:
    dateFormat: "02.01"

  math:
    enable: true

  search:
    enable: true
    type: "lunr"
    contentLength: 4000
    placeholder: ''
    maxResultLength: 10
    snippetLength: 30
    highlightTag: "em"
    absoluteURL: false
    algolia:
      index: ''
      appID: ''
      searchKey: ''

  home:
    rss: 10
    profile:
      title: ''
      subtitle: ''
      
  page:
    rssFullText: true
    share:
      enable: false
    math:
      enable: true
      inlineLeftDelimiter: ""
      inlineRightDelimiter: ""
      blockLeftDelimiter: ""
      blockRightDelimiter: ""
      copyTex: true
      mhchem: false
    code:
      copy: true
      maxShownLines: 50

markup:
  highlight:
    noClasses: false

outputs:
  home: ["HTML","RSS","JSON"]