baseURL: 'https://ateon.ch'
title: Ateon
theme: LoveIt
languageCode: en
languageName: English
author:
  name: gewlar

menu:
  main:
    - weight: 1
      identifier: posts
      pre: ''
      post: ''
      name: Posts
      url: /posts/
      title: ''

params:
  defaultTheme: auto
  dateFormat: 02.01.2006
  title: Ateon
  description: Ateon

  header:
    title:
      name: Ateon

  footer:
    hugo: false
    since: 2021

  social:
    github: gewlar
    LinkedIn: luca-schafroth-a7b9b0129
    RSS: true
    
  app:
    title: Ateon

  section:
    dateFormat: "02.01"
  list:
    dateFormat: "02.01"

  search:
    enable: true
    type: lunr
    contentLength: 4000
    placeholder: ''
    maxResultLength: 10
    snippetLength: 30
    highlightTag: em
    absoluteURL: false
    algolia:
      index: ''
      appID: ''
      searchKey: ''

  home:
    rss: 10
    profile:
      title: ''
      subtitle: ''
      
  page:
    share:
      enable: false
markup:
  highlight:
    noClasses: false
